### ISSUE TITLE
[request] - Automatically parse song title

### ISSUE THREAD

**Issue by duraki** [NegatioN/music_consolidator#1]
Awesome tool, wanted to make something similar few months ago when I've got bored of using `youtube-mp3` and then transferring the songs manually.

Could you implement a way to automatically parse YouTube titles. Most songs have a separator like: `Eminem - The way I am`. If you search for common split pattern (for e.g. `-`), one could add songs much easily. 
  
Sometimes, song have titles like: `The way I am - Eminem` so a button to switch one with other (title w/ artist and vice versa) would be 🔥 .

Also, support for a batch transfer (multiple links) would be nice. Example:

```
https://www.youtube.com/watch?v=DYznR62QvIw
https://www.youtube.com/watch?v=5KjnI9lcFQhIw
```

Another issue I've seen is that `ffmpeg` requirement is not listed neither in `readme` or `requirements.txt` (I had to install it manually).
  
Cheers.

**Comment by NegatioN** [comment]
Thanks for the well-written issue, it's cool that people care! :)
I'm still considering adding some sort of auto-parsing of artist/title, but I think this would only have to be treated as a suggestion, rather than a truth. (because there's a lot less consitency in naming schemes of songs on youtube. In ordering and separators) If I get around to implementing it , it would be as some sort of callback to update the form after the link has been filled in. Will easily accept PRs for this.

It feels like batch-adds rely a bit on the auto-parse?

I'll fix some better docs though ;)

**Comment by NegatioN** [comment]
Made #4 since @mattcheah implemented automatic title-parsing! :)
